version: "3.5"


services:
  redis:
    image: redis
    container_name: redis_dev
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres_dev
    ports:
      - "5433:5432"
    env_file:
      - .env.dev.postgres
    volumes:
      - ./postgres-init-db.sh:/docker-entrypoint-initdb.d/postgres-init-db.sh
      - ./postgres_data_dev/:/var/lib/postgresql/data


#  adminer:
#    image: adminer
#    container_name: adminer_dev
#    restart: unless-stopped
#    ports:
#      - 8080:8080

# TODO containerise celery worker


  metabase:
      image: metabase/metabase:v0.45.1
      container_name: metabase_dev
      ports:
      - "3002:3000"
      env_file:
          - .env.dev.postgres
      depends_on:
          - postgres

  superset:
      container_name: superset_dev
      build:
          context: superset
          dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "8088:8088"
      depends_on:
        - postgres
      volumes:
#          - ./docker:/app/docker
          - superset_home:/app/superset_home
      env_file:
        - .env.dev.postgres


volumes:
  redis_data:
  superset_home:



