"""empty message

Revision ID: 02fbdd452539
Revises: a6314050f86a
Create Date: 2022-08-05 00:09:05.825306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fbdd452539'
down_revision = 'a6314050f86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'is_deleted')
    # ### end Alembic commands ###
