"""changed date and integer types

Revision ID: 044adc025fce
Revises: 8bf47a63b883
Create Date: 2022-08-17 10:04:17.287405

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '044adc025fce'
down_revision = '8bf47a63b883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('number_employees',
                              existing_type=sa.VARCHAR(),
                              type_=sa.Integer(),
                              existing_nullable=True,
                              postgresql_using="number_employees::integer",
                              )
        batch_op.alter_column('main_country_number_employees',
                              existing_type=sa.VARCHAR(),
                              type_=sa.Integer(),
                              existing_nullable=True,
                              postgresql_using="number_employees::integer",
                              )

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
                              existing_type=sa.VARCHAR(),
                              type_=sa.Date(),
                              existing_nullable=True,
                              postgresql_using="date_posted::date",
                              )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
                              existing_type=sa.Date(),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('main_country_number_employees',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)
        batch_op.alter_column('number_employees',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)

    # ### end Alembic commands ###
