"""add column job_categories to SearchModel

Revision ID: 22eec5c2354e
Revises: 1b2f14b2177c
Create Date: 2022-12-27 03:22:52.799549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22eec5c2354e'
down_revision = '1b2f14b2177c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SearchModel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_categories', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SearchModel', schema=None) as batch_op:
        batch_op.drop_column('job_categories')

    # ### end Alembic commands ###
