"""update table names to lowercase

Revision ID: 3644ce0394fd
Revises: 044adc025fce
Create Date: 2022-08-21 18:03:12.316265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3644ce0394fd'
down_revision = '044adc025fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what', sa.String(), nullable=True),
    sa.Column('where', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_email', sa.String(), nullable=True),
    sa.Column('linkedin_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_board_name', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('search_model_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['search_model_id'], ['search_model.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('search_model')
    # ### end Alembic commands ###
