"""replace IgnoreCompany to CompanyUserNote

Revision ID: 3d9cfb0b912d
Revises: cc079d92ee37
Create Date: 2022-09-28 11:31:30.105137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9cfb0b912d'
down_revision = 'cc079d92ee37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_user_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_watched', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ignore_company')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.create_table('ignore_company',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='ignore_company_company_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ignore_company_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ignore_company_pkey')
    )
    op.drop_table('company_user_note')
    # ### end Alembic commands ###
