"""add column task.timestamp

Revision ID: 3ffc7a349a57
Revises: 8d2d9cebe348
Create Date: 2022-08-27 21:26:22.486037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffc7a349a57'
down_revision = '8d2d9cebe348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
