"""add Search-Job relationship

Revision ID: 6c6b1e50a88a
Revises: 044adc025fce
Create Date: 2022-08-20 14:41:26.207845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6b1e50a88a'
down_revision = '044adc025fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('number_employees', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('main_country_name', sa.String(), nullable=True),
    sa.Column('main_country_number_employees', sa.Integer(), nullable=True),
    sa.Column('other_locations_employees', sa.String(), nullable=True),
    sa.Column('other_locations_employees_html', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Company_homepage_url'), ['homepage_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_Company_profile_url'), ['profile_url'], unique=False)

    op.create_table('SearchModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what', sa.String(), nullable=True),
    sa.Column('where', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_email', sa.String(), nullable=True),
    sa.Column('linkedin_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('estimated_salary', sa.String(), nullable=True),
    sa.Column('created_str', sa.String(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('multiple_candidates', sa.String(), nullable=True),
    sa.Column('benefits', sa.String(), nullable=True),
    sa.Column('description_markdown', sa.String(), nullable=True),
    sa.Column('description_text', sa.String(), nullable=True),
    sa.Column('description_html', sa.String(), nullable=True),
    sa.Column('hiring_insights', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('plan_apply_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('did_apply_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Job_url'), ['url'], unique=False)

    op.create_table('Search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_board_name', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_url')

    op.drop_table('job')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('ix_company_homepage_url')
        batch_op.drop_index('ix_company_profile_url')

    op.drop_table('company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('company_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overview', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_locations_employees', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_locations_employees_html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('main_country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_country_number_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('ix_company_profile_url', ['profile_url'], unique=False)
        batch_op.create_index('ix_company_homepage_url', ['homepage_url'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimated_salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('multiple_candidates', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_posted', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('qualifications', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('benefits', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_markdown', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hiring_insights', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plan_apply_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('did_apply_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='job_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_pkey')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_url', ['url'], unique=False)

    op.drop_table('Search')
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Job_url'))

    op.drop_table('Job')
    op.drop_table('User')
    op.drop_table('SearchModel')
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Company_profile_url'))
        batch_op.drop_index(batch_op.f('ix_Company_homepage_url'))

    op.drop_table('Company')
    # ### end Alembic commands ###
