"""add column job.original_url

Revision ID: 6ce45ef300b8
Revises: dcc3e1ca4ac4
Create Date: 2023-03-16 14:17:59.240718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce45ef300b8'
down_revision = 'dcc3e1ca4ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###
