"""add search_model.experience

Revision ID: 85605630ccd2
Revises: 9143c56db953
Create Date: 2022-08-28 00:26:26.549403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85605630ccd2'
down_revision = '9143c56db953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_model', schema=None) as batch_op:
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
