"""add apply flags and note fields

Revision ID: 8bf47a63b883
Revises: 8c98a1d12a05
Create Date: 2022-08-07 13:49:11.207631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf47a63b883'
down_revision = '8c98a1d12a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('plan_apply_flag', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('job', sa.Column('did_apply_flag', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('job', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'note')
    op.drop_column('job', 'did_apply_flag')
    op.drop_column('job', 'plan_apply_flag')
    # ### end Alembic commands ###
