"""capitalize table names

Revision ID: 8fa437b24302
Revises: 3d9cfb0b912d
Create Date: 2022-09-28 12:29:58.711257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa437b24302'
down_revision = '3d9cfb0b912d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('number_employees', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('main_country_name', sa.String(), nullable=True),
    sa.Column('main_country_number_employees', sa.Integer(), nullable=True),
    sa.Column('other_locations_employees', sa.String(), nullable=True),
    sa.Column('other_locations_employees_html', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.Column('timestamp_created', sa.DateTime(), nullable=True),
    sa.Column('timestamp_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Company_homepage_url'), ['homepage_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_Company_profile_url'), ['profile_url'], unique=False)

    op.create_table('SearchModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what', sa.String(), nullable=True),
    sa.Column('where', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('experience', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), server_default='unnamed', nullable=False),
    sa.Column('linkedin_email', sa.String(), nullable=True),
    sa.Column('linkedin_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CompanyUserNote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_watched', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('estimated_salary', sa.String(), nullable=True),
    sa.Column('created_str', sa.String(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('multiple_candidates', sa.String(), nullable=True),
    sa.Column('benefits', sa.String(), nullable=True),
    sa.Column('description_markdown', sa.String(), nullable=True),
    sa.Column('description_text', sa.String(), nullable=True),
    sa.Column('description_html', sa.String(), nullable=True),
    sa.Column('hiring_insights', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('plan_apply_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('did_apply_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('timestamp_created', sa.DateTime(), nullable=True),
    sa.Column('timestamp_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Job_url'), ['url'], unique=False)

    op.create_table('Search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_board_name', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('search_model_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Job.id'], ),
    sa.ForeignKeyConstraint(['search_model_id'], ['SearchModel.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['Task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_url')

    op.drop_table('search')
    op.drop_table('job')
    op.drop_table('search_model')
    op.drop_table('task')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('ix_company_homepage_url')
        batch_op.drop_index('ix_company_profile_url')

    op.drop_table('company_user_note')
    op.drop_table('company')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_user_note',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_filtered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_watched', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='company_user_note_company_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='company_user_note_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='company_user_note_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('linkedin_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), server_default=sa.text("'unnamed'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('search',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_board_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('search_model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='search_job_id_fkey'),
    sa.ForeignKeyConstraint(['search_model_id'], ['search_model.id'], name='search_search_model_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='search_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='search_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='search_pkey')
    )
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('company_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overview', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_locations_employees', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_locations_employees_html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('main_country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_country_number_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('ix_company_profile_url', ['profile_url'], unique=False)
        batch_op.create_index('ix_company_homepage_url', ['homepage_url'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_table('search_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('what', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('where', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('radius', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='search_model_pkey')
    )
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimated_salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('multiple_candidates', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_posted', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('qualifications', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('benefits', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_markdown', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hiring_insights', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plan_apply_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('did_apply_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('timestamp_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='job_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_pkey')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_url', ['url'], unique=False)

    op.drop_table('Search')
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Job_url'))

    op.drop_table('Job')
    op.drop_table('CompanyUserNote')
    op.drop_table('User')
    op.drop_table('Task')
    op.drop_table('SearchModel')
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Company_profile_url'))
        batch_op.drop_index(batch_op.f('ix_Company_homepage_url'))

    op.drop_table('Company')
    # ### end Alembic commands ###
