"""add relationships SearchModel-Search, Task-Search

Revision ID: 93c462a944e5
Revises: 3c984d20ff92
Create Date: 2022-08-20 15:33:35.420576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c462a944e5'
down_revision = '3c984d20ff92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Search', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_model_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'SearchModel', ['search_model_id'], ['id'])
        batch_op.create_foreign_key(None, 'Task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Search', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('task_id')
        batch_op.drop_column('search_model_id')

    op.drop_table('Task')
    # ### end Alembic commands ###
