"""add JobUserNote table

Revision ID: ec7a3b51ac13
Revises: 8fa437b24302
Create Date: 2022-09-28 14:41:07.655249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7a3b51ac13'
down_revision = '8fa437b24302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JobUserNote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('plan_apply_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('did_apply_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_filtered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('plan_apply_flag')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('did_apply_flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('did_apply_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('plan_apply_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('JobUserNote')
    # ### end Alembic commands ###
