"""replace column job_categories to job_category in SearchModel

Revision ID: ef40572e7580
Revises: 22eec5c2354e
Create Date: 2022-12-27 04:37:05.060265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef40572e7580'
down_revision = '22eec5c2354e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SearchModel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_category', sa.Integer(), nullable=True))
        batch_op.drop_column('job_categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SearchModel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_categories', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.drop_column('job_category')

    # ### end Alembic commands ###
