"""add missing columns

Revision ID: a6314050f86a
Revises: b3d3d845272d
Create Date: 2022-08-04 03:18:10.907331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6314050f86a'
down_revision = 'b3d3d845272d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('number_employees', sa.String(), nullable=True))
    op.add_column('company', sa.Column('main_country_name', sa.String(), nullable=True))
    op.add_column('company', sa.Column('main_country_number_employees', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'main_country_number_employees')
    op.drop_column('company', 'main_country_name')
    op.drop_column('company', 'number_employees')
    # ### end Alembic commands ###
