fields = {
    'title': None,
    'url': None,
    'company': {
        'name': None,
        'rating': None,
        'location': None,
        'profile_url': None,
        'overview': None,
        'homepage_url': None,
        'industry': None,
        'size': None,
        'other_locations_employees': None,
        'other_locations_employees_html': None,
    },
    'estimated_salary': None,
    'salary': None,
    'job_type': None,
    'multiple_candidates': None,
    'date_posted': None,
    'qualifications': None,
    'benefits': None,
    'description_markdown': None,
    'description_text': None,
    'description_html': None,
    'hiring_insights': None,
}
